knp_snappy:
    pdf:
        enabled:    true
        binary: '%env(WKHTMLTOPDF_PATH)%'
        options:
            encoding: 'utf-8'
            enable-local-file-access: true
    image:
        enabled:    true
        binary:     '%env(WKHTMLTOIMAGE_PATH)%'
        options:    []
